# Generated by Django 4.1 on 2023-04-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                ("prove", models.CharField(max_length=500)),
                ("slug", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("tel", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Modele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_minimum", models.IntegerField()),
                ("airbag", models.CharField(max_length=50)),
                ("capacitie", models.FloatField()),
                ("attach_cat", models.CharField(max_length=40)),
                ("clim", models.BooleanField()),
                ("denomination", models.IntegerField()),
                ("marque", models.CharField(max_length=40)),
                ("nb_passag", models.IntegerField()),
                ("nb_perms", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("version", models.IntegerField()),
                ("cat", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50)),
                (
                    "Agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.agence",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.modele",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateStart", models.DateField()),
                ("dateEnd", models.DateField()),
                ("tarif", models.CharField(max_length=50)),
                ("statusPayment", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.client",
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myappvoiture.voiture",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="car",
            field=models.ManyToManyField(
                through="myappvoiture.Reservation", to="myappvoiture.voiture"
            ),
        ),
    ]
